name: Build job
# Cloned from tachiyomi
on:
  # Every Saturday at 16:00 UTC-5
  #schedule:
  #  - cron: '0 21 * * 0,3'
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        description: Creates a draft release
        required: false

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'shosetsuorg/shosetsu'
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'shosetsuorg/shosetsu'
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Prepare build
        run: |
          set -e

          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV

          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^r//")
          commit_count_diff=$(expr $commit_count - $prev_commit_count)
          prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)
          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV

          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/shosetsuorg/shosetsu/compare/$prev_release_sha...$current_sha" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_ENV

      - name: Build APK
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleStandardDebug
      
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/build/outputs/apk/standard/debug/
          signingKeyBase64: ${{ secrets.DEBUG_KEYSTORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }} 

      - name: Clean up build artifacts
        run: |
          set -e

          cp android/build/outputs/apk/standard/debug/shosetsu-preview-standard-universal-debug-signed.apk shosetsu-r${{ env.COMMIT_COUNT }}-universal.apk
          sha=`sha256sum shosetsu-r${{ env.COMMIT_COUNT }}-universal.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp android/build/outputs/apk/standard/debug/shosetsu-preview-standard-x86-debug-signed.apk shosetsu-r${{ env.COMMIT_COUNT }}-x86.apk
          sha=`sha256sum shosetsu-r${{ env.COMMIT_COUNT }}-x86.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

          cp android/build/outputs/apk/standard/debug/shosetsu-preview-standard-x86_64-debug-signed.apk shosetsu-r${{ env.COMMIT_COUNT }}-x86_64.apk
          sha=`sha256sum shosetsu-r${{ env.COMMIT_COUNT }}-x86_64.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

          cp android/build/outputs/apk/standard/debug/shosetsu-preview-standard-arm64-v8a-debug-signed.apk shosetsu-r${{ env.COMMIT_COUNT }}-zarm64-v8a.apk
          sha=`sha256sum shosetsu-r${{ env.COMMIT_COUNT }}-zarm64-v8a.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp android/build/outputs/apk/standard/debug/shosetsu-preview-standard-armeabi-v7a-debug-signed.apk shosetsu-r${{ env.COMMIT_COUNT }}-zarmeabi-v7a.apk
          sha=`sha256sum shosetsu-r${{ env.COMMIT_COUNT }}-zarmeabi-v7a.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          name: Shosetsu Preview r${{ env.COMMIT_COUNT }}
          body: |
            ### Commits

            https://github.com/shosetsuorg/shosetsu/compare/${{ env.PREV_RELEASE_SHA }}...${{ env.CURRENT_SHA }}

            ${{ env.COMMIT_LOGS }}

            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | x86 | ${{ env.APK_X86_SHA }}
            | x86_64 | ${{ ENV.APK_X86_64_SHA }}
            | zarm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | zarmeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }} |
          files: |
            shosetsu-r${{ env.COMMIT_COUNT }}-universal.apk
            shosetsu-r${{ env.COMMIT_COUNT }}-x86.apk
            shosetsu-r${{ env.COMMIT_COUNT }}-x86_64.apk
            shosetsu-r${{ env.COMMIT_COUNT }}-zarm64-v8a.apk
            shosetsu-r${{ env.COMMIT_COUNT }}-zarmeabi-v7a.apk
          draft: ${{ github.event.inputs.dry-run != '' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 28
          delete_tags: true
