name: Build job
# Cloned from tachiyomi
on:
  # Every Saturday at 16:00 UTC-5
  schedule:
    - cron: '0 21 * * 0,3'
  # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        description: Creates a draft release
        required: false

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'shosetsuorg/android-app'
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'shosetsuorg/android-app'
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APK
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.DEBUG_KEYSTORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }} 
      
      - name: Set env variables
        run: |
          set -x
          echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          echo "CURRENT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          release_name: Shosetsu Preview r${{ env.COMMIT_COUNT }}
          body: >
            r${{ env.COMMIT_COUNT }}
            Latest commit: https://github.com/shosetsuorg/android-app/commit/${{ env.CURRENT_SHA }}
          draft: ${{ github.event.inputs.dry-run != '' }}
          prerelease: false
      
      - name: Upload APK to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'android/build/outputs/apk/debug/shosetsu-v1.2.0-r${{ env.COMMIT_COUNT }}.apk'
          asset_name: shosetsu-r${{ env.COMMIT_COUNT }}.apk
          asset_content_type: application/vnd.android.package-archive
          
      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 10
          delete_tags: true
